# Generated by Django 6.0 on 2025-12-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='artesanias/')),
                ('categoria', models.CharField(choices=[('trinket', 'Trinket Dish'), ('pin', 'Pin'), ('aro', 'Aro / Arete'), ('colgante', 'Colgante'), ('llavero', 'Llavero'), ('sticker', 'Sticker'), ('iman', 'Imán')], max_length=100)),
            ],
        ),
    ]
