# Generated by Django 6.0 on 2025-12-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tecnologia', models.CharField(help_text='Python, Django, C++, ROOT, SQL…', max_length=200)),
                ('github', models.URLField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
            ],
        ),
    ]
