# Generated by Django 6.0 on 2025-12-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artesanias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('trinket', 'Trinket Dish'), ('pin', 'Pin'), ('aro', 'Aro / Arete'), ('colgante', 'Colgante'), ('llavero', 'Llavero'), ('sticker', 'Sticker'), ('iman', 'Imán'), ('colgante', 'Colgante'), ('hippers', 'Hippers')], max_length=100),
        ),
    ]
